/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const AddLazyImport = createFileRoute('/add')()
const IndexLazyImport = createFileRoute('/')()
const NoteuuidIndexLazyImport = createFileRoute('/$note_uuid/')()
const NoteuuidEditLazyImport = createFileRoute('/$note_uuid/edit')()

// Create/Update Routes

const AddLazyRoute = AddLazyImport.update({
  path: '/add',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/add.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const NoteuuidIndexLazyRoute = NoteuuidIndexLazyImport.update({
  path: '/$note_uuid/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/$note_uuid/index.lazy').then((d) => d.Route),
)

const NoteuuidEditLazyRoute = NoteuuidEditLazyImport.update({
  path: '/$note_uuid/edit',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/$note_uuid/edit.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/add': {
      id: '/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AddLazyImport
      parentRoute: typeof rootRoute
    }
    '/$note_uuid/edit': {
      id: '/$note_uuid/edit'
      path: '/$note_uuid/edit'
      fullPath: '/$note_uuid/edit'
      preLoaderRoute: typeof NoteuuidEditLazyImport
      parentRoute: typeof rootRoute
    }
    '/$note_uuid/': {
      id: '/$note_uuid/'
      path: '/$note_uuid'
      fullPath: '/$note_uuid'
      preLoaderRoute: typeof NoteuuidIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  AddLazyRoute,
  NoteuuidEditLazyRoute,
  NoteuuidIndexLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/add",
        "/$note_uuid/edit",
        "/$note_uuid/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/add": {
      "filePath": "add.lazy.tsx"
    },
    "/$note_uuid/edit": {
      "filePath": "$note_uuid/edit.lazy.tsx"
    },
    "/$note_uuid/": {
      "filePath": "$note_uuid/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
