/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const AddLazyImport = createFileRoute('/add')()
const IndexLazyImport = createFileRoute('/')()
const UuidIndexLazyImport = createFileRoute('/$uuid/')()
const UuidEditLazyImport = createFileRoute('/$uuid/edit')()

// Create/Update Routes

const AddLazyRoute = AddLazyImport.update({
  path: '/add',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/add.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const UuidIndexLazyRoute = UuidIndexLazyImport.update({
  path: '/$uuid/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/$uuid/index.lazy').then((d) => d.Route))

const UuidEditLazyRoute = UuidEditLazyImport.update({
  path: '/$uuid/edit',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/$uuid/edit.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/add': {
      id: '/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AddLazyImport
      parentRoute: typeof rootRoute
    }
    '/$uuid/edit': {
      id: '/$uuid/edit'
      path: '/$uuid/edit'
      fullPath: '/$uuid/edit'
      preLoaderRoute: typeof UuidEditLazyImport
      parentRoute: typeof rootRoute
    }
    '/$uuid/': {
      id: '/$uuid/'
      path: '/$uuid'
      fullPath: '/$uuid'
      preLoaderRoute: typeof UuidIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  AddLazyRoute,
  UuidEditLazyRoute,
  UuidIndexLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/add",
        "/$uuid/edit",
        "/$uuid/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/add": {
      "filePath": "add.lazy.tsx"
    },
    "/$uuid/edit": {
      "filePath": "$uuid/edit.lazy.tsx"
    },
    "/$uuid/": {
      "filePath": "$uuid/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
